### ISSUE TITLE
Regrading to visualization results in the papaer

### ISSUE THREAD

**Issue by yeongjoonJu** [NJUNLP/x-LLM#2]
First of all, thank you for your work.

I wonder details for an experiment of visualization in your paper. (Fig. 5)

How did you project vectors for a sentence for visualizations?

**Comment by OwenNJU** [comment]
Hi, we take hidden states from LLM's last layer and use the averaged vector as the sentence representation

**Comment by yeongjoonJu** [comment]
Thank you for your answer!

I'll refer to embedding.py for more details.
